### ISSUE TITLE
first LED is in the corner bottom right

### ISSUE THREAD

**Issue by SkylightXD** [leinich/ha-wordclock-esphome#5]
Hi Leinich,

erstmal vielen Dank für dieses Projekt 👍 
Ich habe mich sehr gefreut, dass es auch eine Worduhr mit Home Assistant Anbindung gibt! 😄 

Da meine Hardware schon stand, aber meine Stripe unten rechts beginnt, habe ich deine Dateien angepasst 😄 

Aber leider ohne Erfolg ...
Laut Logs ist alles in Ordnung:
[21:36:00][E][loop:119]: Got time from current_time Time: 21:36
[21:36:00][D][loop:134]: Update Time: 21:36  Brightness: 89 RGB: 255-0-0
[21:36:00][D][loop:135]: Using tmp_hour: 10 tmp_minute: 7 minutessum: 1

Aber die Uhr verändert sich nicht ... 
Per HA kann ich die Farben aller LEDs ändern.
Ich nutze nur 110 LED, habe also keine Minuten oder Statuus anzeigen.

Hast du eine Idee, woran das liegen könnte?

Hier mein Code:

wordclock_startuntenrechts.yaml
```
esphome:
  name: wordclock
  includes:
    - wordclock_startuntenrechts.h
  on_boot:
    priority: 800
    then:
      - light.turn_on: 
          id: fastledlight

esp8266:
  board: d1_mini
  framework:
    version: 2.7.4
          
substitutions:
  devicename: wordclock
  friendly_name: "Wordclock"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "ESPhome-Wordclock"
    password: "fdvlnhFRHsdbd35894" 

api:

ota:

logger:
  esp8266_store_log_strings_in_flash: false

light:
  - platform: fastled_clockless
    id: fastledlight
    chipset: WS2812
    pin: GPIO02
    num_leds: 125
    rgb_order: GRB
    name: "WordClock"
  
#time:
#  - platform: homeassistant
#    id: current_time
    
time:
  - platform: homeassistant
    id: homeassistant_time

custom_component:
- lambda: |-
    auto wordclock = new Wordclock();
    return {wordclock};
```

wordclock_startuntenrechts.h
```
#include "esphome.h"
#include <FastLED.h>

#define NUM_LEDS 125
#define DATA_PIN D4

// esphome dependencies:
// needs: esphome time --> id: current_time
// needs: esphome fastled --> id: fastledlight

// Layout of Clock (X not used chars) - PIN Layout
// ESXISTXFÜNF    109.......99
// ZEHNZWANZIG    98......88
// DREIVIERTEL    87......77
// XXNACHVORXX    74......68
// HALBXZWÖLFX    64......56
// ZWEIXSIEBEN    ....
// XDREIXXFÜNF    ....
// ELFNEUNVIER    ....
// XACHTZEHNRS    ....
// XSECHSXXUHR    9.......0




int leds_time_it_is[] = {109, 108, 106, 105, 104}; // ES IST
int leds_minutes[] = {124, 123, 122, 121}; // Minutes LEDS
int leds_skiped[] = {110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120}; // Check Line 101
int leds_time_minutes[][15] = {
    {  0,   1,   2,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1}, // UHR
    {102, 101, 100,  99,  74,  73,  72,  71,  -1,  -1,  -1,  -1,  -1,  -1,  -1}, // FÜNF, NACH
    { 98,  97,  96,  95,  74,  73,  72,  71,  -1,  -1,  -1,  -1,  -1,  -1,  -1}, // ZEHN, NACH
    { 83,  82,  81,  80,  79,  78,  77,  74,  73,  72,  71,  -1,  -1,  -1,  -1}, // VIERTEL, NACH
    { 94,  93,  92,  91,  90,  89,  88,  74,  73,  72,  71,  -1,  -1,  -1,  -1}, // ZWANZIG, NACH
    {102, 101, 100,  99,  70,  69,  68,  65,  64,  63,  62,  -1,  -1,  -1,  -1}, // FÜNF, VOR, HALB
    { 65,  64,  63,  62,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1}, // HALB
    {102, 101, 100,  99,  74,  73,  72,  71,  65,  64,  63,  62,  -1,  -1,  -1}, // FÜNF, NACH, HALB
    { 94,  93,  92,  91,  90,  89,  88,  70,  69,  68,  -1,  -1,  -1,  -1,  -1}, // ZWANZIG, VOR
    { 87,  86,  85,  84,  83,  82,  81,  80,  79,  78,  77,  -1,  -1,  -1,  -1}, // DREIVIERTEL
    { 98,  97,  96,  95,  70,  69,  68, -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1}, // ZEHN, VOR
    {102, 101, 100,  99,  70,  69,  68,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1}  // FÜNF, VOR
};

int leds_time_hours[][6] = {
    { 60,  59,  58,  57,  56,  -1}, // ZWÖLF
    { 52,  51,  50,  49,  -1,  -1}, // EINS
    { 54,  53,  52,  51,  -1,  -1}, // ZWEI
    { 42,  41,  40,  39,  -1,  -1}, // DREI
    { 25,  24,  23,  22,  -1,  -1}, // VIER
    { 36,  35,  34,  33,  -1,  -1}, // FÜNF
    {  9,   8,   7,   6,   5,  -1}, // SECHS
    { 49,  48,  47,  46,  45,  44}, // SIEBEN
    { 20,  19,  18,  17,  -1,  -1}, // ACHT
    { 29,  28,  27,  26,  -1,  -1}, // NEUN
    { 16,  15,  14,  13,  -1,  -1}, // ZEHN
    { 32,  31,  30,  -1,  -1,  -1}  // ELF
};

CRGB leds[NUM_LEDS];
int hour = -1;
int minute = -1;
int red = 124;
int green = 124;
int blue = 124;
int brightness = 50;

class Wordclock : public Component, public CustomAPIDevice {
    public:
        void setup() override {
            FastLED.addLeds<NEOPIXEL, DATA_PIN>(leds, NUM_LEDS);
            FastLED.setBrightness(brightness);
            // Start all LED with on and default color and brightness to check if everything is working...
            for(int i = 0; i < NUM_LEDS; i++) { leds[i].setRGB(red, 0, 0); FastLED.show(); delay(10); }
            for(int i = 0; i < NUM_LEDS; i++) { leds[i].setRGB(0, green, 0); FastLED.show(); delay(10); }
            for(int i = 0; i < NUM_LEDS; i++) { leds[i].setRGB(0, 0, blue); FastLED.show(); delay(10); }
            for(int i = 0; i < NUM_LEDS; i++) { leds[i].setRGB(0, 0, 0); }
            FastLED.show();
            register_service(&Wordclock::on_setled, "setled", {"number","red", "blue", "green"});
        }
        void on_setled(int number, int red, int blue, int green) {
            if (number < NUM_LEDS || number > 0) {
                ESP_LOGD("setled", "Setting led number %d to color %i %i %i", number, red, green, blue );
                leds[number].setRGB(red, green, blue);
                FastLED.show();
                }
            else { ESP_LOGE("setled", "Not a valid LED Number - out of range"); }
        }
        void loop() override {
            // auto time = id(current_time).now();
            auto time = id(homeassistant_time).now();
            int h = time.hour;
            int m = time.minute;
            //ESP_LOGE("loop", "Got time from current_time Time: %i:%i", h, m );
            // https://www.esphome.io/api/classesphome_1_1light_1_1_light_color_values.html LightColorValues Class
            auto fastledlight2 = id(fastledlight).current_values;
            //convert float 0.0 till 1.0 into int 0 till 255
            red = (int)(fastledlight2.get_red()*255);
            green = (int)(fastledlight2.get_green()*255);
            blue = (int)(fastledlight2.get_blue()*255);
            brightness = 0;
            //check if light is on and set brightness
            if (fastledlight2.get_state() > 0 ) { brightness = (int)(fastledlight2.get_brightness()*255); }
            else { ESP_LOGD("loop", "fastledlight state off - b: %i rgb %i %i %i", brightness, red, green, blue); delay(500);}
            FastLED.setBrightness(brightness);
            //check if valid time. Blink red,green,blue until valid time is present
            if (time.is_valid() == false) {
                ESP_LOGE("loop", "Got invalid time from current_time Time: %i:%i", h, m );
                leds[0].setRGB(255, 0, 0); FastLED.show(); delay(250);
                leds[0].setRGB(0, 255, 0); FastLED.show(); delay(250);
                leds[0].setRGB(0, 0, 255); FastLED.show(); delay(250);
                leds[0].setRGB(0, 0, 0);   FastLED.show();
            }
            else {
                // only update once in a Minute
                if(h != hour || m != minute) {
                   //ESP_LOGD("loop", "Using b: %i rgb %i %i %i", brightness, red, green, blue);
                    hour = h;
                    minute = m;
                    ESP_LOGE("loop", "Got time from current_time Time: %i:%i", h, m );
                    if (hour >= 0 && time.is_valid() == true){
                        int tmp_hour = hour;
                        int tmp_minute = (minute - (minute % 5));
                        if(tmp_minute >= 25) { tmp_hour += 1; }
                        tmp_minute = tmp_minute / 5;
                        tmp_hour = tmp_hour % 12;
                        int minutessum = minute % 5;
                        // Reset all LED, but skip LED 110 till 120
                        for(int i = 0; i < NUM_LEDS; i++) {     if(i < 110 || i > 120) leds[i].setRGB(0, 0, 0); }
                        for(int i = 0; i < 5; i++) {            leds[leds_time_it_is[i]].setRGB(red, green, blue); }
                        for(int i = 0; i < 15; i++) {           if(leds_time_minutes[tmp_minute][i] >= 0) { leds[leds_time_minutes[tmp_minute][i]].setRGB(red, green, blue); } }
                        for(int i = 0; i < 6; i++) {            if(leds_time_hours[tmp_hour][i] >= 0) { leds[leds_time_hours[tmp_hour][i]].setRGB(red, green, blue); } }
                        for(int i = 0; i < minutessum; i++) {   leds[leds_minutes[i]].setRGB(red, green, blue);}
                        FastLED.show();
                        ESP_LOGD("loop", "Update Time: %i:%i  Brightness: %i RGB: %i-%i-%i", hour, minute, brightness, red, green, blue);
                        ESP_LOGD("loop", "Using tmp_hour: %i tmp_minute: %i minutessum: %i", tmp_hour, tmp_minute, minutessum);
                    }
                }
            }
        }
};
```

Danke und Grüße

**Comment by leinich** [comment]
@SkylightXD 

Diese Zeile siht ja schon mal gut aus.
[21:36:00][D][loop:134]: Update Time: 21:36 Brightness: 89 RGB: 255-0-0
Hier müssen die LEDS für die Uhrzeit in Rot aufleuchten.

Wenn du den ESP am Strom anschließts, leuchten dann alles LEDS einmal in rot, dann in Grün und abschließend in blau auf?

**Comment by SkylightXD** [comment]
@leinich ne, leider nicht... Das habe ich auch in deinem Code gelesen.
Ich kann bisher nur eine Farbe für alle per HA einstellen... 

Ich glaube mittlerweile, dass es an der Pin Definition im h-File liegt ... 
Mein Board ist dein D1 Mini und ich habe den WS2812 Stripe an D4 / GPIO2 angeschlossen

Spannenderweise passen die Definitionen in deinem Code auch nicht zusammen 
h-File mit D5, das entspricht GPIO14
yaml-File mit GPIO3, das entspricht RX

**Comment by SkylightXD** [comment]
Ich habe in der yaml Datei den light pin auf GPIO03 gesetzt, wie in deiner Version, jetzt geht es
pin: GPIO03

@leinich Warum??? 😄

**Comment by SkylightXD** [comment]
Jetzt klappt es!
Ich hatte im Code noch einen Dreher in der LED Reihenfolge

yaml-File
```
esphome:
  name: wordclock
  includes:
    - wordclock_startuntenrechts.h
  on_boot:
    priority: 800
    then:
      - light.turn_on: 
          id: fastledlight

esp8266:
  board: d1_mini
  framework:
    version: 2.7.4
          
substitutions:
  devicename: wordclock
  friendly_name: "Wordclock"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "ESPhome-Wordclock"
    password: "fdvlnhFRHsdbd35894" 

api:

ota:

logger:
  esp8266_store_log_strings_in_flash: false

light:
  - platform: fastled_clockless
    id: fastledlight
    chipset: WS2812
    pin: GPIO03
    num_leds: 125
    rgb_order: GRB
    name: "WordClock"
  
#time:
#  - platform: homeassistant
#    id: current_time
    
time:
  - platform: homeassistant
    id: homeassistant_time

custom_component:
- lambda: |-
    auto wordclock = new Wordclock();
    return {wordclock};
```

h-File
```
#include "esphome.h"
#include <FastLED.h>

#define NUM_LEDS 125
#define DATA_PIN D5

// esphome dependencies:
// needs: esphome time --> id: current_time
// needs: esphome fastled --> id: fastledlight

// Layout of Clock (X not used chars) - PIN Layout
// ESXISTXFÜNF    109.......99
// ZEHNZWANZIG    98......88
// DREIVIERTEL    87......77
// XXNACHVORXX    74......68
// HALBXZWÖLFX    64......56
// ZWEIXSIEBEN    ....
// XDREIXXFÜNF    ....
// ELFNEUNVIER    ....
// XACHTZEHNRS    ....
// XSECHSXXUHR    9.......0




int leds_time_it_is[] = { 99, 100, 102, 103, 104}; // ES IST
int leds_minutes[] = {124, 123, 122, 121}; // Minutes LEDS
int leds_skiped[] = {110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120}; // Check Line 101
int leds_time_minutes[][15] = {
    {  0,   1,   2,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1}, // UHR
    {106, 107, 108, 109,  74,  73,  72,  71,  -1,  -1,  -1,  -1,  -1,  -1,  -1}, // FÜNF, NACH
    { 98,  97,  96,  95,  74,  73,  72,  71,  -1,  -1,  -1,  -1,  -1,  -1,  -1}, // ZEHN, NACH
    { 81,  82,  83,  84,  85,  86,  87,  74,  73,  72,  71,  -1,  -1,  -1,  -1}, // VIERTEL, NACH
    { 94,  93,  92,  91,  90,  89,  88,  74,  73,  72,  71,  -1,  -1,  -1,  -1}, // ZWANZIG, NACH
    {106, 107, 108, 109,  70,  69,  68,  55,  56,  57,  58,  -1,  -1,  -1,  -1}, // FÜNF, VOR, HALB
    { 55,  56,  57,  58,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1}, // HALB
    {106, 107, 108, 109,  74,  73,  72,  71,  55,  56,  57,  58,  -1,  -1,  -1}, // FÜNF, NACH, HALB
    { 94,  93,  92,  91,  90,  89,  88,  70,  69,  68,  -1,  -1,  -1,  -1,  -1}, // ZWANZIG, VOR
    { 87,  86,  85,  84,  83,  82,  81,  80,  79,  78,  77,  -1,  -1,  -1,  -1}, // DREIVIERTEL
    { 98,  97,  96,  95,  70,  69,  68,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1}, // ZEHN, VOR
    {106, 107, 108, 109,  70,  69,  68,  -1,  -1,  -1,  -1,  -1,  -1,  -1,  -1}  // FÜNF, VOR
};

int leds_time_hours[][6] = {
    { 60,  61,  62,  63,  64,  -1}, // ZWÖLF
    { 52,  51,  50,  49,  -1,  -1}, // EINS
    { 54,  53,  52,  51,  -1,  -1}, // ZWEI
    { 34,  35,  36,  37,  -1,  -1}, // DREI
    { 25,  24,  23,  22,  -1,  -1}, // VIER
    { 40,  41,  42,  43,  -1,  -1}, // FÜNF
    {  9,   8,   7,   6,   5,  -1}, // SECHS
    { 49,  48,  47,  46,  45,  44}, // SIEBEN
    { 12,  13,  14,  15,  -1,  -1}, // ACHT
    { 29,  28,  27,  26,  -1,  -1}, // NEUN
    { 16,  17,  18,  19,  -1,  -1}, // ZEHN
    { 32,  31,  30,  -1,  -1,  -1}  // ELF
};

CRGB leds[NUM_LEDS];
int hour = -1;
int minute = -1;
int red = 124;
int green = 124;
int blue = 124;
int brightness = 50;

class Wordclock : public Component, public CustomAPIDevice {
    public:
        void setup() override {
            FastLED.addLeds<NEOPIXEL, DATA_PIN>(leds, NUM_LEDS);
            FastLED.setBrightness(brightness);
            // Start all LED with on and default color and brightness to check if everything is working...
            for(int i = 0; i < NUM_LEDS; i++) { leds[i].setRGB(red, 0, 0); FastLED.show(); delay(10); }
            for(int i = 0; i < NUM_LEDS; i++) { leds[i].setRGB(0, green, 0); FastLED.show(); delay(10); }
            for(int i = 0; i < NUM_LEDS; i++) { leds[i].setRGB(0, 0, blue); FastLED.show(); delay(10); }
            for(int i = 0; i < NUM_LEDS; i++) { leds[i].setRGB(0, 0, 0); }
            FastLED.show();
            register_service(&Wordclock::on_setled, "setled", {"number","red", "blue", "green"});
        }
        void on_setled(int number, int red, int blue, int green) {
            if (number < NUM_LEDS || number > 0) {
                ESP_LOGD("setled", "Setting led number %d to color %i %i %i", number, red, green, blue );
                leds[number].setRGB(red, green, blue);
                FastLED.show();
                }
            else { ESP_LOGE("setled", "Not a valid LED Number - out of range"); }
        }
        void loop() override {
            // auto time = id(current_time).now();
            auto time = id(homeassistant_time).now();
            int h = time.hour;
            int m = time.minute;
            //ESP_LOGE("loop", "Got time from current_time Time: %i:%i", h, m );
            // https://www.esphome.io/api/classesphome_1_1light_1_1_light_color_values.html LightColorValues Class
            auto fastledlight2 = id(fastledlight).current_values;
            //convert float 0.0 till 1.0 into int 0 till 255
            red = (int)(fastledlight2.get_red()*255);
            green = (int)(fastledlight2.get_green()*255);
            blue = (int)(fastledlight2.get_blue()*255);
            brightness = 0;
            //check if light is on and set brightness
            if (fastledlight2.get_state() > 0 ) { brightness = (int)(fastledlight2.get_brightness()*255); }
            else { ESP_LOGD("loop", "fastledlight state off - b: %i rgb %i %i %i", brightness, red, green, blue); delay(500);}
            FastLED.setBrightness(brightness);
            //check if valid time. Blink red,green,blue until valid time is present
            if (time.is_valid() == false) {
                ESP_LOGE("loop", "Got invalid time from current_time Time: %i:%i", h, m );
                leds[0].setRGB(255, 0, 0); FastLED.show(); delay(250);
                leds[0].setRGB(0, 255, 0); FastLED.show(); delay(250);
                leds[0].setRGB(0, 0, 255); FastLED.show(); delay(250);
                leds[0].setRGB(0, 0, 0);   FastLED.show();
            }
            else {
                // only update once in a Minute
                if(h != hour || m != minute) {
                   //ESP_LOGD("loop", "Using b: %i rgb %i %i %i", brightness, red, green, blue);
                    hour = h;
                    minute = m;
                    ESP_LOGE("loop", "Got time from current_time Time: %i:%i", h, m );
                    if (hour >= 0 && time.is_valid() == true){
                        int tmp_hour = hour;
                        int tmp_minute = (minute - (minute % 5));
                        if(tmp_minute >= 25) { tmp_hour += 1; }
                        tmp_minute = tmp_minute / 5;
                        tmp_hour = tmp_hour % 12;
                        int minutessum = minute % 5;
                        // Reset all LED, but skip LED 110 till 120
                        for(int i = 0; i < NUM_LEDS; i++) {     if(i < 110 || i > 120) leds[i].setRGB(0, 0, 0); }
                        for(int i = 0; i < 5; i++) {            leds[leds_time_it_is[i]].setRGB(red, green, blue); }
                        for(int i = 0; i < 15; i++) {           if(leds_time_minutes[tmp_minute][i] >= 0) { leds[leds_time_minutes[tmp_minute][i]].setRGB(red, green, blue); } }
                        for(int i = 0; i < 6; i++) {            if(leds_time_hours[tmp_hour][i] >= 0) { leds[leds_time_hours[tmp_hour][i]].setRGB(red, green, blue); } }
                        for(int i = 0; i < minutessum; i++) {   leds[leds_minutes[i]].setRGB(red, green, blue);}
                        FastLED.show();
                        ESP_LOGD("loop", "Update Time: %i:%i  Brightness: %i RGB: %i-%i-%i", hour, minute, brightness, red, green, blue);
                        ESP_LOGD("loop", "Using tmp_hour: %i tmp_minute: %i minutessum: %i", tmp_hour, tmp_minute, minutessum);
                    }
                }
            }
        }
};
```
